# Generated by Django 3.2 on 2021-12-25 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
