# Generated by Django 4.1.2 on 2022-10-23 01:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='profile', variations={'thumb': (500, 500, True)}, verbose_name='Image'),
        ),
    ]
