# Generated by Django 4.1.2 on 2022-10-23 01:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='post/imagem', variations={'thumb': (420, 280, True)}, verbose_name='Imagem'),
        ),
    ]
