# Generated by Django 3.2.5 on 2021-10-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211012_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(blank=True, choices=[('ad', 'Administrador'), ('co', 'Colaborador'), ('us', 'Usuario Padrão')], max_length=2, null=True, verbose_name='type_user'),
        ),
    ]
