# Generated by Django 3.2.9 on 2021-12-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
