# Generated by Django 3.2.8 on 2021-10-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='download_file',
        ),
    ]
