# Generated by Django 3.2.9 on 2021-11-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211119_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_user',
        ),
        migrations.AddField(
            model_name='post',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
