# Generated by Django 3.2.8 on 2021-10-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_file_post_download_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='download_file',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link Download'),
        ),
    ]
