# Generated by Django 3.2.8 on 2021-10-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_download_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='download_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link Download'),
        ),
        migrations.AlterField(
            model_name='post',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='post/file'),
        ),
    ]
